version: "3.3"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
  # database:
  #   image: mysql:5.7
  #   env_file:
  #     - .env
  #   ports:
  #     - "3306:3306"
